/*===========================================================================+
 |  HISTORY                                                                  
 |                                                                           
 |  DATE       DEVELOPER     WR       DESCRIPTION                               
 |  ====       =========     ==       =========== 
 |             L Jovanovic            Initial Creation.                 
 |  26-MAY-09  S Douglas              Updated to add constant for lead count
 |                                 
 +===========================================================================*/
public class EMC_CONSTANTS {

    /*************  TEST METHOD CONSTANTS ****************/
    public static final String ACCOUNT_HIER_CONTACT_COUNT = 'ACCOUNT_HIER.CONTACT_COUNT';
    public static final String ACCOUNT_HIER_PROFILE_PRESENCE_IND = 'ACCOUNT_HIER.PROFILE_PRESENCE_IND';
    public static final String ACCOUNT_HIER_LEAD_COUNT = 'ACCOUNT_HIER.LEAD_COUNT';
    public static final String ACCOUNT_HIER_ACCT_PLAN_PRESENCE_IND = 'ACCOUNT_HIER.ACCT_PLAN_PRESENCE_IND';

}